---
- name: make sure git is installed
  package:
    name: git
    state: present

- name: fetch fzf from github
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: /tmp/fzf/
    version: HEAD # latest

- name: Run install script
  script: /tmp/fzf/install --no-key-bindings --no-completion --no-update-rc
