---
- name: Install Fzf from Brew
  homebrew:
    name: fzf
    state: present

- name: Run install script
  script: /opt/homebrew/opt/fzf/install --no-update-rc

- name: Copy FZF configuration
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.fzf.zsh"
    src: ".fzf.zsh"
