---
- name: Install Tmux
  community.general.homebrew:
    name: tmux
    state: present

- name: Creates Tmux Plugin Manager(tpm) directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir}}/.tmux/plugins/"
    state: directory

- name: Clone Tmux Plugin Manager(tpm)
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir}}/.tmux/plugins/tpm"
    repo: https://github.com/tmux-plugins/tpm
    single_branch: yes
    update: yes
    version: master

- name: Copy tmux config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    src: ".tmux.conf"
