---
- name: Tap Homebrew repositories
  homebrew_tap:
    name: "neovim/neovim"

- name: Install Homebrew packages
  homebrew:
    name: "neovim"
    update_homebrew: yes

- name: Clone Pigeon-nvim
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/nvim"
    repo: https://github.com/abdielrumaldo/pigeon-nvim 
    single_branch: yes
    update: yes

