---
- name: Tap Homebrew repositories
  homebrew_tap:
    name: "neovim/neovim"

- name: Install Homebrew packages
  homebrew:
    name: "neovim"
    update_homebrew: yes

- name: Delete existing nvim folder
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: absent

- name: Clone Pigeon-nvim
  ansible.builtin.git:
    clone: yes
    dest: "{{ ansible_user_dir }}/.config/nvim"
    repo: https://github.com/abdielrumaldo/nvim.git  
    update: yes
